### ISSUE TITLE
module departemen

### ISSUE THREAD

**Issue by nurisakbar** [nurisakbar/aplikasi-pengelolaan-diklat-P4TK#2]
buatlah sebuah module CRUD data departemen dengan struktur seperti berikut :    
nama tabel : departemen
field : id, nama_departemen,created_at, updated_at

## TASK
- [x] Menampilkan data departemen
- [x] menambah departemen
- [x] menhapus departemen
- [x] mengubah departemen
- [x] hubungkan data departemen dengan diklat, ubah field departemen menjadi departemen_id pada tabel diklat, kemudian buat relasi belongsto pada model diklat
- [x] pada detail diklat, perbaiki infromasi data departemen

**Comment by nurisakbar** [comment]
1. ubah dropdown departemen dengan data dari tabel departemen
<img width="1438" alt="Screen Shot 2021-12-29 at 21 45 35" src="https://user-images.githubusercontent.com/5483330/147673992-97eacddc-11ab-456f-bee2-ddfe4841ec51.png">

2. pada detail diklat tambahkan informasi departemen nya
