### ISSUE TITLE
akses mandiri oleh guru

### ISSUE THREAD

**Issue by nurisakbar** [nurisakbar/aplikasi-pengelolaan-diklat-P4TK#6]
selain di daftarkan oleh admin, guru juga bisa melakukan pendaftaran mandiri pada halaman web dan nantinya harus di approve oleh admin agar guru tersebut bisa melakukan login.
adapun jika data guru tersebut sudah ada maka guru bisa melakukan login dengan menggunakan email dan nopes sebagai credensial.

## TASK

- [ ] buat sebuah halaman pendaftaran untuk guru dengan URL : /pendaftaran
- [ ] adapun data yang harus di isin adalah : nama, nik, nopes, sekolah ( pakai select2 ajax dengan data dari tabel sekolah ), alamat,no_hp, jabatan ( textbox )
- [ ] setelah button pendaftaran disubmit makan akan muncul konfirmasi terima kasih dan silahkan menunggu akun anda di approvle oleh admin ( ketika pertama kali di insert field is_approved nya 0 )
- [ ] maka admin akan melakukan login , pada module gtk muncul informasi guru yang akunya harus di konfirmasi, admn bisa melihat detail dan ada button aprove untuk mengubah status nya menjadi aktif ( is_approved menjadi 1 )
